
export const ALL_MEDICINES = [
    {
        id: 1,
        name: 'Amoxicillin',
        dosage: '500mg',
        type: 'Antibiotic',
        manufacturer: 'PharmaCorp',
        image: '💊',
        batch: 'BATCH-2025-001',
        verified: true,
    },
    {
        id: 2,
        name: 'Ibuprofen',
        dosage: '400mg',
        type: 'Pain Reliever',
        manufacturer: 'HealthMed',
        image: '💊',
        batch: 'BATCH-2025-004',
        verified: true,
    },
    {
        id: 3,
        name: 'Paracetamol',
        dosage: '500mg',
        type: 'Analgesic',
        manufacturer: 'WellnessInc',
        image: '💊',
        batch: 'BATCH-2025-012',
        verified: true,
    },
    {
        id: 4,
        name: 'Omeprazole',
        dosage: '20mg',
        type: 'Antacid',
        manufacturer: 'PharmaCorp',
        image: '💊',
        batch: 'BATCH-2025-009',
        verified: true,
    },
    {
        id: 5,
        name: 'Metformin',
        dosage: '500mg',
        type: 'Antidiabetic',
        manufacturer: 'BioLife',
        image: '💊',
        batch: 'BATCH-2025-022',
        verified: true,
    },
    {
        id: 6,
        name: 'Atorvastatin',
        dosage: '10mg',
        type: 'Cardiovascular',
        manufacturer: 'HealthMed',
        image: '💊',
        batch: 'BATCH-2025-015',
        verified: true,
    },
    {
        id: 7,
        name: 'Amlodipine',
        dosage: '5mg',
        type: 'Cardiovascular',
        manufacturer: 'HeartCare',
        image: '💊',
        batch: 'BATCH-2025-033',
        verified: true,
    },
    {
        id: 8,
        name: 'Lisinopril',
        dosage: '10mg',
        type: 'Cardiovascular',
        manufacturer: 'PharmaCorp',
        image: '💊',
        batch: 'BATCH-2025-041',
        verified: true,
    },
    {
        id: 9,
        name: 'Levothyroxine',
        dosage: '50mcg',
        type: 'Hormone',
        manufacturer: 'BioLife',
        image: '💊',
        batch: 'BATCH-2025-055',
        verified: true,
    },
    {
        id: 10,
        name: 'Azithromycin',
        dosage: '250mg',
        type: 'Antibiotic',
        manufacturer: 'HealthMed',
        image: '💊',
        batch: 'BATCH-2025-067',
        verified: true,
    },
    {
        id: 11,
        name: 'Simvastatin',
        dosage: '20mg',
        type: 'Cardiovascular',
        manufacturer: 'WellnessInc',
        image: '💊',
        batch: 'BATCH-2025-078',
        verified: true,
    },
    {
        id: 12,
        name: 'Losartan',
        dosage: '50mg',
        type: 'Cardiovascular',
        manufacturer: 'HeartCare',
        image: '💊',
        batch: 'BATCH-2025-089',
        verified: true,
    },
    {
        id: 13,
        name: 'Gabapentin',
        dosage: '300mg',
        type: 'Anticonvulsant',
        manufacturer: 'NeuroPharma',
        image: '💊',
        batch: 'BATCH-2025-092',
        verified: true,
    },
    {
        id: 14,
        name: 'Hydrochlorothiazide',
        dosage: '12.5mg',
        type: 'Diuretic',
        manufacturer: 'PharmaCorp',
        image: '💊',
        batch: 'BATCH-2025-104',
        verified: true,
    },
    {
        id: 15,
        name: 'Montelukast',
        dosage: '10mg',
        type: 'Antiasthmatic',
        manufacturer: 'RespiratoryCare',
        image: '💊',
        batch: 'BATCH-2025-118',
        verified: true,
    }
];
